### PR TITLE
Enable Python tools in Docker Image

### PR DESCRIPTION
**Pull request by tcwan**
Dockerfile to enable Python tools (python, scons) for ev3dev/debian-stretch-cross

### CODE REVIEW

**Comment by dlech** [comment]
So, what will this be used for? And who will be using it?

**Comment by tcwan** [comment]
It is needed to build ev3dev-c. I plan to roll out for use with my course once we actually get EV3 kits for the university (this process take a while though).

**Comment by dlech** [comment]
I think it would be better if this Dockerfile was in the ev3dev-c repository since that is what it is used for.

**Comment by tcwan** [comment]
Ok. That is fine as well.
Is there a way to cancel a pull request?

**Comment by dlech** [comment]
Just close it.

**Pull request closed without merging**
